const constants = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  LOGOUT: 'LOGOUT',

  SET_USER: 'SET_USER',
  CLEAR_ERRORS: 'CLEAR_ERRORS',

  GET_ALL_BLOGS_PENDING: 'GET_ALL_BLOGS_PENDING',
  GET_ALL_BLOGS_SUCCESS: 'GET_ALL_BLOGS_SUCCESS',
  GET_ALL_BLOGS_FAILED: 'GET_ALL_BLOGS_FAILED',
};

export default constants;
